// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbelgxrazmuqspzsrxsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiZWxneHJhem11cXNwenNyeHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMTI4NTgsImV4cCI6MjA2ODc4ODg1OH0.pu_ZgB-i8foaJmuhLllsiUT0K7zFkcwqjBW5scv6fPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});